name: "Release"

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build-chromium:
    name: "Build Chromium"
    runs-on: ubuntu-latest

    environment: "Release"

    steps:
      - uses: actions/checkout@v7

      - name: "Pack extension"
        env:
          CRX_KEY: ${{ secrets.CRX_KEY }}
        run: |
          key="$(mktemp)"
          echo "$CRX_KEY" | base64 -d > "$key"
          trap 'rm -f "$key"' EXIT INT TERM

          src="$(mktemp -d)"
          trap 'rm -rf "$src"' EXIT INT TERM

          cp *.js *.html manifest.json "$src/"

          chromium --no-message-box --no-sandbox \
            --pack-extension="$src" \
            --pack-extension-key="$key"

          mv "$src.crx" "extension.crx"

      - uses: actions/attest@v4
        with:
          subject-path: extension.crx

      - uses: actions/upload-artifact@v7
        with:
          path: extension.crx
          archive: false

  build-mozilla:
    name: "Build Mozilla"
    runs-on: ubuntu-latest

    environment: "Release"

    steps:
      - uses: actions/checkout@v7

      - name: "Install web-ext"
        run: npm i -g web-ext

      - name: "Pack extension"
        env:
          WEB_EXT_API_KEY: ${{ secrets.MOZ_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.MOZ_SECRET }}
        run: |
          src="$(mktemp -d)"
          out="$(mktemp -d)"
          trap 'rm -rf "$src" "$out"' EXIT INT TERM

          cp *.js *.html "$src/"
          jq 'del(.incognito)' manifest.json > "$src/manifest.json"

          web-ext sign \
            --source-dir "$src" \
            --artifacts-dir "$out" \
            --channel unlisted

          mv "$out"/*.xpi "extension.xpi"

      - uses: actions/attest@v4
        with:
          subject-path: extension.xpi

      - uses: actions/upload-artifact@v7
        with:
          path: extension.xpi
          archive: false
